# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 02:02
from __future__ import unicode_literals

from django.db import migrations
import csv
from django.template.defaultfilters import slugify


def mainst_vendor_import(apps, schema_editor):
    Vendor = apps.get_model("review_app", "Vendor")
    FarmersMarket = apps.get_model("review_app", "FarmersMarket")
    with open("review_app/data/gvl_mainst_vendors.csv") as infile:
        ms_vendors = csv.reader(infile)
        fm = FarmersMarket.objects.get(fm_name="TD Saturday Market")
        for row in ms_vendors:
            vendor_slug = slugify(row[0])
            vendor = Vendor.objects.create(vendor_name=row[0], vendor_slug=vendor_slug,
            vendor_description=row[1], vendor_website=row[2])
            # http://stackoverflow.com/questions/12764347/django-invalid-keyword-argument-for-this-function
            vendor.save()
            vendor.at_farmers_market.add(fm)

    # raise Exception("2 yay")

def tr_vendor_import(apps, schema_editor):
    Vendor = apps.get_model("review_app", "Vendor")
    FarmersMarket = apps.get_model("review_app", "FarmersMarket")
    VendorType = apps.get_model("review_app", "VendorType")
    with open("review_app/data/tr_vendors.csv") as infile:
        tr_vendors = csv.reader(infile)
        fm = FarmersMarket.objects.get(fm_name="Travelers Rest Farmers Market")
        for row in tr_vendors:
            vendor_slug = slugify(row[1])
            vendor_type = VendorType.objects.get(id=row[0])
            vendor = Vendor.objects.create(
            vendor_name=row[1], vendor_slug=vendor_slug,
            vendor_description=row[2], vendor_type=vendor_type
            )
            vendor.save()
            vendor.at_farmers_market.add(fm)

    # raise Exception("2 yay")

class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_auto_20160720_0200'),
    ]

    operations = [
        migrations.RunPython(tr_vendor_import),
        migrations.RunPython(mainst_vendor_import),
    ]
